# ---------- Stage 1 : Build React App ----------
FROM node:22-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files first (better cache)
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy project source
COPY . .

# Build production app
RUN npm run build


# ---------- Stage 2 : Run with Nginx ----------
FROM nginx:stable-alpine

# Remove default nginx files
RUN rm -rf /usr/share/nginx/html/*

# Copy build output from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose container port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
